# Generated by Django 4.0.6 on 2022-07-21 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaTrabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha_registro',
            field=models.DateField(verbose_name='Fecha de registro'),
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellido_paterno', models.CharField(max_length=200)),
                ('apellido_materno', models.CharField(max_length=200)),
                ('numero_documento', models.CharField(max_length=200)),
                ('correo', models.CharField(max_length=200)),
                ('celular', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=200)),
                ('ruc', models.CharField(max_length=200)),
                ('fecha_registro', models.DateField(verbose_name='Fecha de registro')),
                ('categoria_trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.categoriatrabajador')),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.tipodocumento')),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=500)),
                ('fechahora_agendada', models.DateTimeField(verbose_name='Fecha y hora agendada')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.cliente')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.trabajador')),
            ],
        ),
    ]
