# Generated by Django 4.0.6 on 2022-07-22 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='peso',
            field=models.IntegerField(default=0),
        ),
    ]
