# Generated by Django 4.0.6 on 2022-07-22 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_producto_categoria_prodcuto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='peso',
            new_name='peso_en_kg',
        ),
    ]
