# Generated by Django 4.0.6 on 2022-07-22 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_producto_field_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='field_name',
        ),
        migrations.AddField(
            model_name='producto',
            name='imagenxd',
            field=models.ImageField(default='#', upload_to='media/productos'),
        ),
    ]
