# Generated by Django 4.0.6 on 2022-07-22 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_alter_producto_imagenxd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='imagenxd',
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default='#', upload_to='productos'),
        ),
    ]
