# Generated by Django 4.0.6 on 2022-07-22 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField(verbose_name='Fecha de registro')),
                ('fuente_lead', models.CharField(choices=[('Referencia personal', 'Referencia personal'), ('Sitio web', 'Sitio web de la empresa'), ('Facebook', 'Red social Facebook'), ('Instagram', 'Red social Instagram'), ('Twitter', 'Red social Twitter'), ('Youtube', 'Red social Youtube')], default=None, max_length=30)),
                ('tipo_documento', models.CharField(choices=[('DNI', 'DNI'), ('CE', 'Carnet de extranjería')], default='DNI', max_length=30)),
                ('numero_documento', models.CharField(max_length=200)),
                ('apellido_paterno', models.CharField(max_length=200)),
                ('apellido_materno', models.CharField(max_length=200)),
                ('nombre', models.CharField(max_length=200)),
                ('ruc', models.CharField(max_length=200)),
                ('razon_social', models.CharField(max_length=200)),
                ('correo', models.CharField(max_length=200)),
                ('celular', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=200)),
                ('url_whatsapp', models.CharField(max_length=200)),
                ('url_facebook', models.CharField(max_length=200)),
                ('url_instagram', models.CharField(max_length=200)),
                ('url_twitter', models.CharField(max_length=200)),
                ('estado_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.estadocliente')),
            ],
        ),
    ]
